/*
 * Omnichannel API
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@messente.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MessageResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * OmniMessageCreateSuccessResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-14T08:47:17.173Z")
public class OmniMessageCreateSuccessResponse {
  @SerializedName("messages")
  private List<MessageResult> messages = null;

  @SerializedName("to")
  private String to = null;

  @SerializedName("omnimessage_id")
  private UUID omnimessageId = null;

  public OmniMessageCreateSuccessResponse messages(List<MessageResult> messages) {
    this.messages = messages;
    return this;
  }

  public OmniMessageCreateSuccessResponse addMessagesItem(MessageResult messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<MessageResult>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @ApiModelProperty(value = "")
  public List<MessageResult> getMessages() {
    return messages;
  }

  public void setMessages(List<MessageResult> messages) {
    this.messages = messages;
  }

  public OmniMessageCreateSuccessResponse to(String to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @ApiModelProperty(value = "")
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }

  public OmniMessageCreateSuccessResponse omnimessageId(UUID omnimessageId) {
    this.omnimessageId = omnimessageId;
    return this;
  }

   /**
   * Get omnimessageId
   * @return omnimessageId
  **/
  @ApiModelProperty(value = "")
  public UUID getOmnimessageId() {
    return omnimessageId;
  }

  public void setOmnimessageId(UUID omnimessageId) {
    this.omnimessageId = omnimessageId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmniMessageCreateSuccessResponse omniMessageCreateSuccessResponse = (OmniMessageCreateSuccessResponse) o;
    return Objects.equals(this.messages, omniMessageCreateSuccessResponse.messages) &&
        Objects.equals(this.to, omniMessageCreateSuccessResponse.to) &&
        Objects.equals(this.omnimessageId, omniMessageCreateSuccessResponse.omnimessageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messages, to, omnimessageId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmniMessageCreateSuccessResponse {\n");
    
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    omnimessageId: ").append(toIndentedString(omnimessageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

