/*
 * Omnichannel API
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@messente.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorResponse;
import io.swagger.client.model.OmniMessageCreateSuccessResponse;
import io.swagger.client.model.Omnimessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OmnimessageApi
 */
@Ignore
public class OmnimessageApiTest {

    private final OmnimessageApi api = new OmnimessageApi();

    
    /**
     * Sends an Omnimessage
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendOmnimessageTest() throws ApiException {
        Omnimessage body = null;
        OmniMessageCreateSuccessResponse response = api.sendOmnimessage(body);

        // TODO: test validations
    }
    
}
