/*
 * Omnichannel API
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@messente.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MessageValidationResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OmniMessageCreateResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-30T13:29:03.525Z")
public class OmniMessageCreateResponse {
  @SerializedName("messages")
  private List<MessageValidationResult> messages = null;

  public OmniMessageCreateResponse messages(List<MessageValidationResult> messages) {
    this.messages = messages;
    return this;
  }

  public OmniMessageCreateResponse addMessagesItem(MessageValidationResult messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<MessageValidationResult>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @ApiModelProperty(value = "")
  public List<MessageValidationResult> getMessages() {
    return messages;
  }

  public void setMessages(List<MessageValidationResult> messages) {
    this.messages = messages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmniMessageCreateResponse omniMessageCreateResponse = (OmniMessageCreateResponse) o;
    return Objects.equals(this.messages, omniMessageCreateResponse.messages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmniMessageCreateResponse {\n");
    
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

