/*
 * Omnichannel API
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DeliveryReportResponse;
import org.openapitools.client.model.ErrorResponse;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeliveryReportApi
 */
@Ignore
public class DeliveryReportApiTest {

    private final DeliveryReportApi api = new DeliveryReportApi();

    
    /**
     * Retrieves the delivery report for the Omnimessage
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveDeliveryReportTest() throws ApiException {
        UUID omnimessageId = null;
        DeliveryReportResponse response = api.retrieveDeliveryReport(omnimessageId);

        // TODO: test validations
    }
    
}
