/*
 * Omnichannel API
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: admin@messente.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.messente.omnichannel;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * SMS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-19T09:45:59.838+03:00")
public class SMS {
  @SerializedName("text")
  private String text = null;

  @SerializedName("autoconvert")
  private BigDecimal autoconvert = null;

  @SerializedName("udh")
  private String udh = null;

  @SerializedName("sender")
  private String sender = null;

  public SMS text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Text content of the SMS
   * @return text
  **/
  @ApiModelProperty(value = "Text content of the SMS")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public SMS autoconvert(BigDecimal autoconvert) {
    this.autoconvert = autoconvert;
    return this;
  }

   /**
   * Defines how non-GSM characters will be treated
   * @return autoconvert
  **/
  @ApiModelProperty(value = "Defines how non-GSM characters will be treated")
  public BigDecimal getAutoconvert() {
    return autoconvert;
  }

  public void setAutoconvert(BigDecimal autoconvert) {
    this.autoconvert = autoconvert;
  }

  public SMS udh(String udh) {
    this.udh = udh;
    return this;
  }

   /**
   * hex-encoded string containing SMS UDH
   * @return udh
  **/
  @ApiModelProperty(value = "hex-encoded string containing SMS UDH")
  public String getUdh() {
    return udh;
  }

  public void setUdh(String udh) {
    this.udh = udh;
  }

  public SMS sender(String sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Phone number or alphanumeric sender name
   * @return sender
  **/
  @ApiModelProperty(value = "Phone number or alphanumeric sender name")
  public String getSender() {
    return sender;
  }

  public void setSender(String sender) {
    this.sender = sender;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SMS SMS = (SMS) o;
    return Objects.equals(this.text, SMS.text) &&
        Objects.equals(this.autoconvert, SMS.autoconvert) &&
        Objects.equals(this.udh, SMS.udh) &&
        Objects.equals(this.sender, SMS.sender);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, autoconvert, udh, sender);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SMS {\n");
    
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    autoconvert: ").append(toIndentedString(autoconvert)).append("\n");
    sb.append("    udh: ").append(toIndentedString(udh)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

